// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authentication-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4075a83a888f0da0, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4075a83a888f0da0, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LoginResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "v1.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "v1.LoginResponse")
}

func init() { proto.RegisterFile("authentication-service.proto", fileDescriptor_4075a83a888f0da0) }

var fileDescriptor_4075a83a888f0da0 = []byte{
	// 395 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0xd5, 0xa6, 0xd0, 0x0f, 0x13, 0x50, 0x31, 0x20, 0x45, 0xab, 0x08, 0x99, 0x3d, 0xa1, 0x88,
	0xac, 0x93, 0x90, 0x53, 0xb8, 0xd0, 0x0a, 0x71, 0xea, 0x69, 0x9b, 0x1b, 0x07, 0xe4, 0x6e, 0x46,
	0x5e, 0xd3, 0xc4, 0xb3, 0x78, 0xc6, 0x09, 0x67, 0x7e, 0x02, 0xdc, 0xf8, 0x51, 0x1c, 0xe0, 0x2f,
	0xf0, 0x43, 0x50, 0x76, 0x93, 0xaa, 0x55, 0x4f, 0x9e, 0x79, 0xef, 0xe9, 0xbd, 0xd1, 0xb3, 0xe8,
	0x9b, 0xc8, 0x15, 0x78, 0x76, 0xa5, 0x61, 0x87, 0x7e, 0x48, 0x10, 0xd6, 0xae, 0x84, 0xbc, 0x0e,
	0xc8, 0x28, 0x3b, 0xeb, 0x71, 0xda, 0xb7, 0x88, 0x76, 0x09, 0xda, 0xd4, 0x4e, 0x1b, 0xef, 0x91,
	0x1b, 0x21, 0xb5, 0x8a, 0xf4, 0x4d, 0xf3, 0x94, 0x43, 0x0b, 0x7e, 0x48, 0x1b, 0x63, 0x2d, 0x04,
	0x8d, 0x75, 0xa3, 0xb8, 0xaf, 0xce, 0x3e, 0x8a, 0xee, 0x05, 0x5a, 0xe7, 0x0b, 0xf8, 0x1a, 0x81,
	0x58, 0xa6, 0xe2, 0x38, 0x12, 0x04, 0x6f, 0x56, 0xd0, 0x4b, 0x54, 0xf2, 0xfa, 0xa4, 0xb8, 0xd9,
	0xb7, 0x5c, 0x6d, 0x88, 0x36, 0x18, 0x16, 0xbd, 0x4e, 0xcb, 0xed, 0xf7, 0xec, 0x42, 0x3c, 0xde,
	0xf9, 0x50, 0x8d, 0x9e, 0x40, 0xf6, 0xc4, 0x11, 0xc5, 0xb2, 0x04, 0xa2, 0xc6, 0xe7, 0xb8, 0xd8,
	0xaf, 0xf2, 0x95, 0xe8, 0x9a, 0x66, 0xfa, 0xcc, 0x78, 0x0d, 0x7e, 0x67, 0xf5, 0xa8, 0xc5, 0xe6,
	0x5b, 0x68, 0xf2, 0x49, 0xbc, 0x38, 0xbb, 0xd3, 0xc2, 0x65, 0x5b, 0x82, 0x3c, 0x17, 0x0f, 0x9b,
	0x18, 0x79, 0x9a, 0xaf, 0xc7, 0xf9, 0xed, 0xcb, 0xd3, 0xa7, 0xb7, 0x90, 0xf6, 0x86, 0xec, 0xf9,
	0xf7, 0xbf, 0xff, 0x7e, 0x76, 0x9e, 0x64, 0x27, 0x7a, 0x3d, 0xd6, 0xcb, 0x2d, 0x35, 0x4b, 0x06,
	0xe7, 0x7f, 0x92, 0x1f, 0x67, 0xbf, 0x13, 0x59, 0x89, 0xee, 0x1c, 0x3f, 0xa0, 0xda, 0xf5, 0x9b,
	0x5d, 0x8a, 0x97, 0x73, 0x20, 0x76, 0xde, 0xaa, 0xbb, 0xd9, 0x6a, 0x1f, 0xde, 0xaf, 0x98, 0x6b,
	0x9a, 0x69, 0x6d, 0x1d, 0x57, 0xf1, 0x2a, 0x2f, 0x71, 0xa5, 0x29, 0xfa, 0xeb, 0x08, 0x3c, 0x9a,
	0xa4, 0xcf, 0x6e, 0xc6, 0xf7, 0x76, 0x65, 0xdc, 0x72, 0x4b, 0x4f, 0x0e, 0xc6, 0xf9, 0x68, 0x90,
	0x24, 0x93, 0x53, 0x53, 0xd7, 0xcb, 0x9d, 0x9f, 0xfe, 0x42, 0xe8, 0x67, 0xf7, 0x90, 0xe2, 0x9d,
	0x38, 0x98, 0x8e, 0xa6, 0x72, 0x2a, 0x06, 0x05, 0x70, 0x0c, 0x1e, 0x16, 0x6a, 0x53, 0x81, 0x57,
	0x5c, 0x81, 0x0a, 0x40, 0x18, 0x43, 0x09, 0x6a, 0x81, 0x40, 0xca, 0x23, 0x2b, 0xf8, 0xe6, 0x88,
	0x73, 0x79, 0x28, 0x1e, 0xfc, 0xea, 0x24, 0x47, 0x57, 0x87, 0xcd, 0x77, 0xbe, 0xfd, 0x1f, 0x00,
	0x00, 0xff, 0xff, 0x10, 0x1f, 0x71, 0x32, 0x3e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthenticationServiceClient is the client API for AuthenticationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthenticationServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type authenticationServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthenticationServiceClient(cc *grpc.ClientConn) AuthenticationServiceClient {
	return &authenticationServiceClient{cc}
}

func (c *authenticationServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/v1.AuthenticationService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthenticationServiceServer is the server API for AuthenticationService service.
type AuthenticationServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

// UnimplementedAuthenticationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthenticationServiceServer struct {
}

func (*UnimplementedAuthenticationServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func RegisterAuthenticationServiceServer(s *grpc.Server, srv AuthenticationServiceServer) {
	s.RegisterService(&_AuthenticationService_serviceDesc, srv)
}

func _AuthenticationService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AuthenticationService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthenticationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.AuthenticationService",
	HandlerType: (*AuthenticationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AuthenticationService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authentication-service.proto",
}
