// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greetings-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SayHelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayHelloRequest) Reset()         { *m = SayHelloRequest{} }
func (m *SayHelloRequest) String() string { return proto.CompactTextString(m) }
func (*SayHelloRequest) ProtoMessage()    {}
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_817d225a2cabed91, []int{0}
}

func (m *SayHelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayHelloRequest.Unmarshal(m, b)
}
func (m *SayHelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayHelloRequest.Marshal(b, m, deterministic)
}
func (m *SayHelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayHelloRequest.Merge(m, src)
}
func (m *SayHelloRequest) XXX_Size() int {
	return xxx_messageInfo_SayHelloRequest.Size(m)
}
func (m *SayHelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SayHelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SayHelloRequest proto.InternalMessageInfo

func (m *SayHelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SayHelloResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SayHelloResponse) Reset()         { *m = SayHelloResponse{} }
func (m *SayHelloResponse) String() string { return proto.CompactTextString(m) }
func (*SayHelloResponse) ProtoMessage()    {}
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_817d225a2cabed91, []int{1}
}

func (m *SayHelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SayHelloResponse.Unmarshal(m, b)
}
func (m *SayHelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SayHelloResponse.Marshal(b, m, deterministic)
}
func (m *SayHelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayHelloResponse.Merge(m, src)
}
func (m *SayHelloResponse) XXX_Size() int {
	return xxx_messageInfo_SayHelloResponse.Size(m)
}
func (m *SayHelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SayHelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SayHelloResponse proto.InternalMessageInfo

func (m *SayHelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SayHelloRequest)(nil), "v1.SayHelloRequest")
	proto.RegisterType((*SayHelloResponse)(nil), "v1.SayHelloResponse")
}

func init() { proto.RegisterFile("greetings-service.proto", fileDescriptor_817d225a2cabed91) }

var fileDescriptor_817d225a2cabed91 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x31, 0x8f, 0xda, 0x30,
	0x18, 0x86, 0x15, 0x40, 0x50, 0xdc, 0xa1, 0x60, 0x2a, 0x95, 0x46, 0x0c, 0x56, 0xa4, 0x4a, 0x15,
	0x82, 0x98, 0xa4, 0x4c, 0x74, 0x69, 0xbb, 0x94, 0xa9, 0x43, 0xe8, 0xd8, 0xc5, 0x84, 0x4f, 0x8e,
	0xdb, 0xc4, 0x4e, 0xf3, 0x39, 0xa1, 0x5d, 0xef, 0x27, 0xdc, 0x6d, 0xf7, 0xa3, 0x6e, 0xb8, 0xfb,
	0x0b, 0xf7, 0x43, 0x4e, 0x84, 0x0b, 0xa7, 0x3b, 0x26, 0x7f, 0x7e, 0xdf, 0x47, 0x7e, 0x5f, 0xf9,
	0x23, 0xef, 0x64, 0x01, 0x60, 0x95, 0x96, 0x38, 0x47, 0x28, 0x2a, 0x15, 0x83, 0x9f, 0x17, 0xc6,
	0x1a, 0xda, 0xaa, 0x02, 0x77, 0x22, 0x8d, 0x91, 0x29, 0x70, 0x91, 0x2b, 0x2e, 0xb4, 0x36, 0x56,
	0x58, 0x65, 0x34, 0x1e, 0x09, 0x77, 0x56, 0x1f, 0xf1, 0x5c, 0x82, 0x9e, 0xe3, 0x5e, 0x48, 0x09,
	0x05, 0x37, 0x79, 0x4d, 0x9c, 0xd3, 0xde, 0x07, 0xf2, 0x66, 0x23, 0xfe, 0xaf, 0x21, 0x4d, 0x4d,
	0x04, 0x7f, 0x4b, 0x40, 0x4b, 0x29, 0xe9, 0x68, 0x91, 0xc1, 0xd8, 0x61, 0xce, 0xc7, 0x7e, 0x54,
	0xcf, 0xde, 0x8c, 0x0c, 0x9e, 0x30, 0xcc, 0x8d, 0x46, 0xa0, 0x63, 0xd2, 0xcb, 0x00, 0x51, 0xc8,
	0x06, 0x6d, 0xae, 0xe1, 0x2f, 0x32, 0xf8, 0xde, 0xf4, 0xdf, 0x1c, 0xeb, 0xd3, 0x35, 0x79, 0xd5,
	0xbc, 0x40, 0x47, 0x7e, 0x15, 0xf8, 0x2f, 0x62, 0xdd, 0xb7, 0xcf, 0xc5, 0x63, 0x88, 0x37, 0xbc,
	0xb8, 0xbb, 0xbf, 0x6a, 0xbd, 0xa6, 0x7d, 0x5e, 0x05, 0x3c, 0x39, 0x58, 0xdf, 0x6e, 0x9d, 0xcb,
	0xaf, 0x37, 0x0e, 0x4d, 0xc8, 0xf0, 0x14, 0xc2, 0x1e, 0x53, 0xbc, 0x1f, 0xe4, 0xfd, 0x4f, 0xc0,
	0x83, 0xc6, 0xce, 0x4c, 0x3a, 0x49, 0xac, 0xcd, 0x71, 0xc5, 0xb9, 0x54, 0x36, 0x29, 0xb7, 0x7e,
	0x6c, 0x32, 0x8e, 0xa5, 0xfe, 0x53, 0x82, 0x5d, 0x84, 0xee, 0xe8, 0x34, 0x7e, 0x91, 0x99, 0x50,
	0xe9, 0xc1, 0x0e, 0xdb, 0x81, 0xbf, 0x98, 0x3a, 0x4e, 0x38, 0x10, 0x79, 0x9e, 0xaa, 0xb8, 0xfe,
	0x3a, 0xfe, 0x1b, 0x8d, 0x5e, 0x9d, 0x29, 0xd1, 0x67, 0xd2, 0x5e, 0x2e, 0x96, 0x74, 0x49, 0xa6,
	0x11, 0xd8, 0xb2, 0xd0, 0xb0, 0x63, 0xfb, 0x04, 0x34, 0xb3, 0x09, 0xb0, 0x02, 0xd0, 0x94, 0x45,
	0x0c, 0x6c, 0x67, 0x00, 0x99, 0x36, 0x96, 0xc1, 0x3f, 0x85, 0xd6, 0xa7, 0x5d, 0xd2, 0xb9, 0x6e,
	0x39, 0xbd, 0x6d, 0xb7, 0x5e, 0xc7, 0xa7, 0x87, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x12, 0xff,
	0x2e, 0xf9, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreetingsServiceClient is the client API for GreetingsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreetingsServiceClient interface {
	SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error)
}

type greetingsServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreetingsServiceClient(cc *grpc.ClientConn) GreetingsServiceClient {
	return &greetingsServiceClient{cc}
}

func (c *greetingsServiceClient) SayHello(ctx context.Context, in *SayHelloRequest, opts ...grpc.CallOption) (*SayHelloResponse, error) {
	out := new(SayHelloResponse)
	err := c.cc.Invoke(ctx, "/v1.GreetingsService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreetingsServiceServer is the server API for GreetingsService service.
type GreetingsServiceServer interface {
	SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
}

// UnimplementedGreetingsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGreetingsServiceServer struct {
}

func (*UnimplementedGreetingsServiceServer) SayHello(ctx context.Context, req *SayHelloRequest) (*SayHelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterGreetingsServiceServer(s *grpc.Server, srv GreetingsServiceServer) {
	s.RegisterService(&_GreetingsService_serviceDesc, srv)
}

func _GreetingsService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetingsServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.GreetingsService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetingsServiceServer).SayHello(ctx, req.(*SayHelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GreetingsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.GreetingsService",
	HandlerType: (*GreetingsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GreetingsService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greetings-service.proto",
}
